### ISSUE TITLE
Deploy to an Existing Virtual Network

### ISSUE THREAD

**Issue by mahthi** [DSPN/azure-arm-dse#29]
The Current template doesn't allow deploying into an existing Virtual Network. Need to allow that.

**Comment by benofben** [comment]
Not sure this is necessary for the Marketplace Template.  This is an advanced feature.  The goal of the template is to get people started quickly.  

It may be useful to discuss goals and intended users of the template.

**Comment by mahthi** [comment]
Not really, Ben. This is a template certification criteria for being in the Azure Marketplace. Since we are the first template to launch, this was a temporary exception for DataStax. ☺

**Comment by benofben** [comment]
We recently had this come up with a customer.  The simple template has been modified so that a variable can be set to deploy to arbitrary vnets.

This isn't really possible in the marketplace template, since there is no way to check for IP conflicts, etc.

**Comment by mahthi** [comment]
It is actually possible to get a contiguous set of IP addresses without any collisions in the marketplace. A simple sample with CreateUIDef that another partner is using is built out here - https://github.com/reyandap/armtemplates/tree/master/cisco-csr-1000v

Let’s talk details of how this works in the marketplace on the next call.

Mahehs

**Comment by benofben** [comment]
Deploys now span multiple vnets for the multidc.  Making this configurable at a parameter level, much less a UI level is going to be untenable.  If a user wants to customize this, they'll need to edit the template.
