### ISSUE TITLE
Deploy Highly Available OpsCenter Nodes

### ISSUE THREAD

**Issue by mahthi** [DSPN/azure-arm-dse#30]
Today, we deploy one opscenter node is susceptible to downtimes. Is it possible to deploy 2 nodes and use the second one for failover?

**Comment by benofben** [comment]
We could deploy multiple OpsCenters.  I'm not sure building that into the template is desirable as that adds considerable complexity.  

OpsCenter is not critical for the functionality of a DSE cluster.  It is merely a monitoring interface.

**Comment by mahthi** [comment]
Is it okay if OpsCenter is down from time to time for more than 30 minutes?

**Comment by stinkymatt** [comment]
OpsCenter did get an HA config option in 5.1. I would consider this a lower priority than some other things, but it would be nice to have for larger clusters.

**Comment by benofben** [comment]
In the new main template I'm putting OpsCenter in its own Vnet/subnet/template functions.  With it compartmentalized, it'll be easy to add additional nodes if desired.  https://github.com/DSPN/azure-resource-manager-dse/issues/42

**Comment by benofben** [comment]
We haven't really been asked for this.  OpsCenter redundancy isn't necessary for a cluster to continue operating.  If the node does fail, it can be replaced manually.  Given all that I'm closing this.
