### ISSUE TITLE
Rack Awareness

### ISSUE THREAD

**Issue by mahthi** [DSPN/azure-arm-dse#31]
Support Rackaware DC configuration by setting up the config file and snitch

**Comment by benofben** [comment]
Let's discuss this on 7/27/15

**Comment by benofben** [comment]
There is an Azure metadata service that is not yet live.  When active, if a VM makes a call to the metadata service, we'll be returned the fault domain and upgrade domain that VM belongs to. There is not a way to specify which fault domain or upgrade domain you want a node to belong to, but the Azure platform makes some rough guarantees about even distribution.

Lets revisit once the metadata service is live.

Here's an example session to the (not yet live) metadata service:
root@opscenter:/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.3.0.0/download/0# curl http://169.254.169.254/metadata/v1/instanceinfo

Bad Requestroot@opscenter:/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.3.0.0/download/0#

**Comment by benofben** [comment]
Here's some initial documentation on the instance metadata service:
https://azure.microsoft.com/en-us/blog/what-just-happened-to-my-vm-in-vm-metadata-service/

Once this is fully rolled out and can return the FD that an instance is part of, we'll add that to the rack variable in the OpsCenter setup scripts.

**Comment by benofben** [comment]
A full fledged snitch solution to this is being tracked here: https://issues.apache.org/jira/browse/CASSANDRA-9387

We'll probably try to fix it in the templates as a stop gap, and the snitch as a better, longer term solution.

**Comment by benofben** [comment]
After some internal discussions, it seems there is a preference to use Gossiping Property File Snitch (GPFS) in many cases rather than developing an Azure specific snitch.  I'm going to look into scripting this up.  It looks like Rich may have already done a lot of that work for me...

**Comment by benofben** [comment]
Looks like Rich has a solution here: https://github.com/richrein/cassandra.bin/blob/master/azure_instance_fault_domain

**Comment by benofben** [comment]
To feed this to OpsCenter, I'll still need to use sshpass or similar to connect to every node, run Rich's script and then write that into the provision.json.  It'll be pretty brittle, but at least it's straightforward to do.

**Comment by benofben** [comment]
This is being done here now: https://github.com/DSPN/install-datastax/blob/master/bin/dse/generate_cassandra_rackdc_properties.sh

**Comment by mahthi** [comment]
Awesome! ☺
