### ISSUE TITLE
Output OpsCenter URL on Provisioning Completion

### ISSUE THREAD

**Issue by mahthi** [DSPN/azure-arm-dse#33]
We can return the Cluster name as output of the template deployment for easier viewing from a customer standpoint.

**Comment by benofben** [comment]
I think they pass the cluster name in.  What might be useful is a more direct way to access the URL where OpsCenter is running.

**Comment by mahthi** [comment]
Yes! That was the idea behind opening the issue. ☺

**Comment by benofben** [comment]
What form would this output take?  Is there a way to present the URL in the Marketplace UI?

I know the terminal prints some variables out on completion.  Is there a way to add the URL to that output?

**Comment by mahthi** [comment]
Yes, we can add the URL to the output.

I don’t think UI is picking up the outputs very well today for display. I want to drive that design as well once we bring it in. ☺

Mahesh

**Comment by benofben** [comment]
Going to add this to the "main" template I'm working on.

**Comment by benofben** [comment]
Currently there is nothing to pick this output up.  Will add this to output once that is available.

**Comment by mahthi** [comment]
Outputs are shown in the Portal after deployment execution. I can walk you through where its shown today. ☺

**Comment by benofben** [comment]
I'm guessing this is how you do this:
https://azure.microsoft.com/en-us/documentation/articles/resource-group-authoring-templates/#outputs

Going to give it a try now...

**Comment by mahthi** [comment]
That’s right! ☺

**Comment by benofben** [comment]
Just did this for simple.  I'll copy it to the others as I complete those.
