### ISSUE TITLE
Understand how we can build better resiliency in Opscenter for temporary node unavailability

### ISSUE THREAD

**Issue by mahthi** [DSPN/azure-arm-dse#34]
When we build out large clusters, the nodes might not be unavailable for a short period of time in case the host decides to move the VM. We need to understand if Opscenter can handle such delays especially in case of large cluster deployments.

**Comment by benofben** [comment]
We can adjust timeouts.  This sounds like a platform concern though.  What period of time are we talking about here? ms, sec, min?

**Comment by mahthi** [comment]
Yes, I was more interested in timeouts. Understanding what opscenter timeouts are configured and how we can work with it to build better resiliency. That’s all. ☺

**Comment by benofben** [comment]
What sort of unresponsiveness are we architecting for here?  If a host moves the VM, how long will things be unresponsive?

**Comment by mahthi** [comment]
Typically, this should be in the order of a few minutes. But In some rare cases, the VM could take an additional 10 minutes to come back online. Not sure if that resiliency can be built in?

**Comment by benofben** [comment]
DataStax has an idea of a hinted handoff.  Essentially a node can go offline and other nodes will keep track of state changes and replay them when the node comes back.  By default the window for this is three hours.  I think this would allow us to work around the issue you mention.

More detail is available here:
http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_about_hh_c.html

**Comment by mahthi** [comment]
But can this be leveraged during provisioning time? I saw that OpsCenter was timing out talking to a node often.

**Comment by benofben** [comment]
I think that might have been the issue related to auto_bootstrap.  We now set that parameter to false in the JSON passed to OpsCenters REST API.

Have you observed failures during the OpsCenter provisioning recently?

**Comment by mahthi** [comment]
Not recently though. Maybe, this might not be an issue anymore and that 3 hour window should cover us.

**Comment by benofben** [comment]
Yeah, I think there are two questions:
(1) Nodes moving hosts --- handled by hinted handoff, etc
(2) Cluster build timing out --- handled by autobootstrap

I've been reliably spinning up 90 node cluster since the most recent changes (specifically the Azul JVM repo one unrelated to this).

**Comment by mahthi** [comment]
Awesome. Thanks.
