### ISSUE TITLE
Multi Datacenter Provision Fails

### ISSUE THREAD

**Issue by InderSingh1** [DSPN/azure-arm-dse#58]
I had customized pointer to a file instead of web url

The original entry:-
 "https://raw.githubusercontent.com/DSPN/azure-resource-manager-dse/master/extensions/opsCenter.py",

Updated in the /home/<my user name>/azure-resource-manager-dse/multidc/opscenter.py file:-
 "file:///home/indersingh/azure-resource-manager-dse/extensions/opsCenter.py",

The error while DSE resources were being created:-
Error Type:
Microsoft.Compute/virtualMachines/extensions

• Resource Id
/subscriptions/<sub id>/resourceGroups/<rs group name>/providers/Microsoft.Compute/virtualMachines/opscenter/extensions/installopscenter

• StatusMessage
{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'installopscenter'. Error message: \"Enable failed: <urlopen error [Errno 2] No such file or directory: '/home/<user name>/azure-resource-manager-dse/extensions/opsCenter.py'>\"."}]}}

What is the best way to implement my customizations (dse data folders and other C\* parameters and be able to implement these changed from my PC to Azure in "multidc". Should I update the online file (git hub) and then download it on my machine and then revert changes online (git hub)?

Or how do I ensure that changes made on my local machine are used by the python script while building the DSE cluster in Azure using these scripts?

Thanks,
Inder

**Comment by benofben** [comment]
Hi Inder,

I'm not sure an extension can point to file://  Azure expects to be able to download extensions from an unsecured http connection at deploy time.  As a result, your extensions need to be on the web somewhere.  GitHub is a convenient place for that.

If you'd like to modify the template my suggestion would be to fork it and then update the baseurl.  From there you can make the changes you need.

Word of warning --- multidc is a work in progress and doesn't complete the opscenter provision properly right now.  I'll probably have that cleaned up in a few days.  We just moved from doing vnet gateways to public IPs based on advise from Azure Engineering and it's exposed more work than I initially expected.

Thanks,
Ben

**Comment by InderSingh1** [comment]
Ben,
I really appreciate your quick response. I need to automate the DSE cluster build under multi data center.
Please let me know when if there is any alternative that I can utilize as base (and customize it as required here) or if there is you have a planned date; from when we can utilize this code (with Opscenter provisioning).

Best Regards,
Inder

**Comment by benofben** [comment]
Sure.  Yes, the current solution would be manual.  Comment out this line so the OpsCenter provision doesn't run:
https://github.com/DSPN/azure-resource-manager-dse/blob/master/extensions/opsCenter.sh#L26

You'll still get the machines, ips, etc all set up.  You would then need to install DSE and configure it using sh scripts or similar.  

Sorry there isn't a nicer solution at the moment.

**Comment by benofben** [comment]
As Inder discovered above, the multi dc provision currently fails.  This is because the OpsCenter agent tries to communicate with OpsCenter on a private IP rather than a public IP.

I'm investigating the best workaround.

**Comment by InderSingh1** [comment]
Hello Ben,

Have you got any update about it yet? I am eagerly waiting for it.

Best Regards,
Inder

**Comment by benofben** [comment]
Hi Inder,

A fix here is probably a few weeks out.  In the meantime you can use the ARM scripts to provision the infrastructure and then use a sh script to install DataStax.  I believe Travis may have provided some examples on that.

Thanks,
Ben

**Comment by InderSingh1** [comment]
Ben, I am familiar with installation of OpsCenter and DSE (Cassandra itself) and can install these on Ubuntu machine. I have done that in AWS environment few times.

I tried to execute the script after commenting out the line per your instructions and it error out. It seems that I will have to do lot more than just commenting out one line (please help me with that). I want to utilize the IPs like 172.<>.120.0 as an example instead of 10.0.0.1 and I also realized that I could not connect to any node (DSE) via putty for some reason (using public ip address). So there seems to be more to it as compared to just commenting out the opscenter related line. 

Any help from you will be great.

Travis mentioned yesterday morning that he will contact one of the resources in Datastax who is familiar with Automation. I realized that you seems to have the solution that comes close to what we are looking for.

I will call Travis as well to see if he has anything else to add to it.

**Comment by benofben** [comment]
I just pushed a bunch of changes that should allow for multi dc provisioning.  We still have some OpsCenter agent issues to work through, but I think this is largely resolved.
