### ISSUE TITLE
Update to DSE 5.0.0 and Opscenter 6.0.0

### ISSUE THREAD

**Issue by markrey** [DSPN/azure-arm-dse#63]
Would it be possible to update the system to the latest DSE and Opscenter ?

Thanks

**Comment by benofben** [comment]
Hi,

Yes, we definitely want to do that.  It only GA'd today, so it's going to take at least a few days.

Thanks,
Ben

**Comment by benofben** [comment]
The ARM templates here are now migrated to 5.0.  We should be updating the marketplace offer shortly.  Let me know if we can assist further.

**Comment by benofben** [comment]
We're encountering some issues with the agents.  The cluster itself seems to come up ok.

**Comment by benofben** [comment]
It all seems to work now for both single and multi dc.  Please let me know if you see any issues.  We'll get the marketplace moved to 5.0 soon too!
