### ISSUE TITLE
Deploy scripts don't work anymore

### ISSUE THREAD

**Issue by jo-tud** [DSPN/azure-arm-dse#77]
`azure` command is now `az` and parameters have changed.

**Comment by mbiciunas** [comment]
I'll second this issue.  Azure CLI v2 uses different command and parameters so deploy.sh does not work.

To recreate, install the new Azure CLI and attempt to install either the multi data center or single data center versions.  Both will fail.

**Comment by cpoczatek** [comment]
Deploy scripts now use CLI v2 command `az`, and fall back to v1 command `azure` if not available.
