### ISSUE TITLE
Timeout issue when deploying large number of nodes

### ISSUE THREAD

**Issue by eadgbear** [DSPN/azure-arm-dse#78]
When trying to use the single DC setup script to deploy 16 DS14_v2 nodes, the script times out after about an hour with the following error:

```
Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningTimeout\",\r\n        \"message\": \"Provisioning of VM extension 'installopscenter' has timed out. Extension installation may be taking too long, or extension status could not be obtained.\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```

The `opscenter` step seems to be the step that is failing. If I use the multi-step method it seems to work better (aside from missing the NSG). I don't seem to run into this error with a lower number of nodes. Is there a way to possibly add nodes at a later time to mitigate this?

**Comment by cpoczatek** [comment]
First I'll try to reproduce. Questions:

- Do the multi-step templates deploy with the same node type and number?

- When the deployment fails what's the status of the `nodes` deployment? There are calls happening between the vm's in both deployments so an error in one ca show as a timeout in the other. I just tried a very large deployment and a quota error around the `nodes` deployment was kinda hidden unless I went to `Resource group -> Deployments -> mainTemplate -> Operation Details`

**Comment by eadgbear** [comment]
Nodes seems pretty reliable, no matter the count. The multi-step deploys with the same SKU and count.

<img width="616" alt="screen shot 2017-10-26 at 6 16 59 pm" src="https://user-images.githubusercontent.com/41403/32083745-ec8e1160-ba79-11e7-91cd-315cbd1bf6fa.png">

The last two steps above will last until the ARM timeout of about an hour and a half.

**Comment by eadgbear** [comment]
Looks like the Jobs part of the opsCenter is timing out.

```
2017/10/27 01:30:46 Jobs running/pending on try 84, sleeping 60 sec...
2017/10/27 01:30:46
2017/10/27 01:30:46 {
2017/10/27 01:30:46     "count": 1,
2017/10/27 01:30:46     "current": 1,
2017/10/27 01:30:46     "last": 1,
2017/10/27 01:30:46     "next": null,
2017/10/27 01:30:46     "per-page": 50,
2017/10/27 01:30:46     "previous": null,
2017/10/27 01:30:46     "results": [
2017/10/27 01:30:46         {
2017/10/27 01:30:46             "cluster-id": "86202983-cb84-457e-b0a0-d37256dc7bde",
2017/10/27 01:30:46             "cluster-name": "mycluster",
2017/10/27 01:30:46             "created-on": "2017-10-27T00:05:17.500Z",
2017/10/27 01:30:46             "datacenter-id": "039f6191-df93-445a-a3ee-f901a04f2945",
2017/10/27 01:30:46             "datacenter-name": "dc0",
2017/10/27 01:30:46             "description": null,
2017/10/27 01:30:46             "dry-run": false,
2017/10/27 01:30:46             "href": "http://localhost:8888/api/v1/lcm/jobs/287b2fcb-b6a8-4eec-a2d0-83255b412b1d",
2017/10/27 01:30:46             "id": "287b2fcb-b6a8-4eec-a2d0-83255b412b1d",
2017/10/27 01:30:46             "job-type": "install",
2017/10/27 01:30:46             "modified-on": "2017-10-27T00:05:19.169Z",
2017/10/27 01:30:46             "node-id": null,
2017/10/27 01:30:46             "node-name": null,
2017/10/27 01:30:46             "related-resources": {
2017/10/27 01:30:46                 "cluster": "http://localhost:8888/api/v1/lcm/clusters/86202983-cb84-457e-b0a0-d37256dc7bde",
2017/10/27 01:30:46                 "datacenter": "http://localhost:8888/api/v1/lcm/datacenters/039f6191-df93-445a-a3ee-f901a04f2945",
2017/10/27 01:30:46                 "job-events": "http://localhost:8888/api/v1/lcm/jobs/287b2fcb-b6a8-4eec-a2d0-83255b412b1d/job_events/",
2017/10/27 01:30:46                 "job-nodes": "http://localhost:8888/api/v1/lcm/jobs/287b2fcb-b6a8-4eec-a2d0-83255b412b1d/job_nodes/"
2017/10/27 01:30:46             },
2017/10/27 01:30:46             "status": "RUNNING",
2017/10/27 01:30:46             "type": "job"
2017/10/27 01:30:46         }
2017/10/27 01:30:46     ]
2017/10/27 01:30:46 }
```

And it looks like that even thought the deployment is timing out whatever script is still running, I'm `tail`-ing the logs on the opsCenter node now.

**Comment by eadgbear** [comment]
Eventually the opsCenter script fails with the following output:

```
2017/10/27 01:46:47 Jobs running/pending on try 100, sleeping 60 sec...
2017/10/27 01:46:47 Maximum attempts, exiting
2017/10/27 01:46:47 Trying:  http://127.0.0.1:8888/meta
2017/10/27 01:46:47 Found OpsCenter version: 6.1.4
2017/10/27 01:46:47 Turn on OpsC auth
2017/10/27 01:46:47 Turn on SSL
2017/10/27 01:46:47 Restart OpsC
2017/10/27 01:46:47 Connect to OpsC after restart...
2017/10/27 01:46:47 Attempt 1...
2017/10/27 01:46:47 Attempt 2...
2017/10/27 01:46:47 Attempt 3...
2017/10/27 01:46:47 Attempt 4...
2017/10/27 01:46:47 Attempt 5...
2017/10/27 01:46:47
2017/10/27 01:46:47 Success retrieving token.
2017/10/27 01:46:47 {"sessionid": "3a1ed34cbd2d0b9a4c7c8c15e797a477"}
2017/10/27 01:46:47 null
2017/10/27 01:46:47 Traceback (most recent call last):
2017/10/27 01:46:47   File "./lcm/alterKeyspaces.py", line 54, in <module>
2017/10/27 01:46:47     main()
2017/10/27 01:46:47   File "./lcm/alterKeyspaces.py", line 24, in main
2017/10/27 01:46:47     cid = clusterconf.keys()[0]
2017/10/27 01:46:47 IndexError: list index out of range
```

**Comment by cpoczatek** [comment]
Ok, I was going to try to reproduce before asking for logs. So Thanks.

If `opscenter.sh` is still running, that's good... This is blocking to do some final cleanup that's done manually in the multi-step version (specificly running `alterKeyspaces.py` and `set_opsc_pw_https.sh). Briefly this is what's going on between the `opscenter` and `nodes` deployments:

- `opscenter vm` <-- REST call --`node vm`
- `opscenter vm` -- ssh --> `node vm` (performs DSE install using Lifecycle Manager)
- `opsCenter.sh` blocks until LCM jobs are finished to run final scripts.

It looks like for this sized cluster it's timing out in the blocking part and the final scripts are run too early. This is "orphaning" the LCM jobs and is probably leaving the cluster in a bad state.

There are work-arounds, but I'm going to have to think a bit to decide what a real solution would be.

**Comment by eadgbear** [comment]
Would editing the template to simulate a multi-step help in any way? Batching adding nodes, etc.

**Comment by eadgbear** [comment]
I tried this on 3 small nodes and got the following:

```
2017/10/27 02:55:01 Jobs running/pending on try 3, sleeping 60 sec...
2017/10/27 02:55:01
2017/10/27 02:55:01 {
2017/10/27 02:55:01     "count": 1,
2017/10/27 02:55:01     "current": 1,
2017/10/27 02:55:01     "last": 1,
2017/10/27 02:55:01     "next": null,
2017/10/27 02:55:01     "per-page": 50,
2017/10/27 02:55:01     "previous": null,
2017/10/27 02:55:01     "results": [
2017/10/27 02:55:01         {
2017/10/27 02:55:01             "cluster-id": "20b02774-0ea5-4068-bf8f-4ff025b94c57",
2017/10/27 02:55:01             "cluster-name": "mycluster",
2017/10/27 02:55:01             "created-on": "2017-10-27T02:50:19.835Z",
2017/10/27 02:55:01             "datacenter-id": "b44e0102-6519-4362-9b03-9f380d290296",
2017/10/27 02:55:01             "datacenter-name": "dc0",
2017/10/27 02:55:01             "description": null,
2017/10/27 02:55:01             "dry-run": false,
2017/10/27 02:55:01             "href": "http://localhost:8888/api/v1/lcm/jobs/ae754ff0-996b-47ae-8319-c9ab8cca9a40",
2017/10/27 02:55:01             "id": "ae754ff0-996b-47ae-8319-c9ab8cca9a40",
2017/10/27 02:55:01             "job-type": "install",
2017/10/27 02:55:01             "modified-on": "2017-10-27T02:53:06.693Z",
2017/10/27 02:55:01             "node-id": null,
2017/10/27 02:55:01             "node-name": null,
2017/10/27 02:55:01             "related-resources": {
2017/10/27 02:55:01                 "cluster": "http://localhost:8888/api/v1/lcm/clusters/20b02774-0ea5-4068-bf8f-4ff025b94c57",
2017/10/27 02:55:01                 "datacenter": "http://localhost:8888/api/v1/lcm/datacenters/b44e0102-6519-4362-9b03-9f380d290296",
2017/10/27 02:55:01                 "job-events": "http://localhost:8888/api/v1/lcm/jobs/ae754ff0-996b-47ae-8319-c9ab8cca9a40/job_events/",
2017/10/27 02:55:01                 "job-nodes": "http://localhost:8888/api/v1/lcm/jobs/ae754ff0-996b-47ae-8319-c9ab8cca9a40/job_nodes/"
2017/10/27 02:55:01             },
2017/10/27 02:55:01             "status": "WILL_FAIL",
2017/10/27 02:55:01             "type": "job"
2017/10/27 02:55:01         }
2017/10/27 02:55:01     ]
2017/10/27 02:55:01 }
```

**Comment by cpoczatek** [comment]
I believe I'm reproducing the same bug you're seeing and putting together a workaround.

**Comment by eadgbear** [comment]
This may be unrelated, but I've had more success after fixing JSON syntax
errors in nodes.json

**Comment by cpoczatek** [comment]
On JSON sytax, these same templates get published in the Azure marketplace/portal so they've been validated in some sense. But you're right, there are a few JSON errors in `nodes.json` that show up in a linter. I'm surprised. However I don't think that's related to the timeouts.

What I've been seeing is a failure of the [LifeCycle Manager](https://docs.datastax.com/en/opscenter/6.1/opsc/LCM/opscLCMOverview.html) install jobs on some nodes when "downloading Java/accepting the Oracle EULA". This is hard to fix in the templates themselves, so I'm working on a fix in our VM image, but that'll take a few days to push through.

If you want, I've tested this work around a few times with success:

- In a browser log into OpsCenter (this is http://opscenter-publicip:8888) and navigate to `LifeCycle Manager -> Jobs`, look for hung jobs at the "Downloading Java and agreeing to EULA" step. Note the ip of these nodes. *Wait for non-hung jobs to complete.* ([doc](https://docs.datastax.com/en/opscenter/6.1/opsc/LCM/opscLCMviewJobDetails.html))
- ssh into the opscenter vm and restart opscenter with `sudo service opscenterd restart`. Bouncing kills the hung jobs and lets the extension script (that should still be running) to set the OpsC pw and turn on https. So you need to wait a bit for that to happen and log back into OpsC.
- For each node that didn't succeed there's going to be a pid file that didn't get cleaned up, so from the OpsC vm for each hung node you need to run: `ssh 10.0.0.6 'sudo rm /var/run/meld.pid'`
- In a browser go to `LCM -> Clusters` run a cluster level install job. ([doc](https://docs.datastax.com/en/opscenter/6.1/opsc/LCM/opscLCMinstallJob.html)) This will go over all the nodes installing on the ones that were hung, and just check things on the others.
- the alterKeyspace script hasn't run at this point and since OpsC auth is on it can't, so to do that the easiest thing is probably to go into OpsC and alter the keyspaces manually to use NetworkTopology and an RF of 3.

**Comment by cpoczatek** [comment]
A fix to the image used by these templates was published today. This should prevent this timeout issue and I can no longer reproduce. The above work around should no longer be necessary.
