### ISSUE TITLE
IP Cluster Size Limitation

### ISSUE THREAD

**Issue by benofben** [DSPN/azure-arm-dse#9]
The template uses a single subnet.  10.0.0.1-10.0.0.4 are reserved by Azure. 10.0.0.5-10.0.0.255 are useable.

10.0.0.5 is currently used by OpsCenter.  10.0.0.6 and up are used by DSE nodes.  So, a maximum of 255-6=249 DSE nodes can be created.  

In the future we'll want to spread deployment over multiple broadcast groups.

**Comment by stinkymatt** [comment]
It is worth noting that 249 is a multiple of 3 and therefore a rack-aware optimal # of nodes for RF=3.

**Comment by benofben** [comment]
Mahesh patched this.  Testing.  See notes here: https://github.com/DSPN/azure-arm-dse/issues/8

**Comment by benofben** [comment]
Azure has a limit of 4096 nodes currently.  18*255=4590.  The current solution should take us to the Azure limit.
